### ISSUE TITLE
Can userlimits be overridden ?

### ISSUE THREAD

**Issue by jrcastillo** [wraithgar/hapi-rate-limit#23]
I'm reading the code to see if a PR can be made where user options can be overridden. 

Wanted to know why the user override options were explicitly deleted ? Since I'm not very familiar with this topic, you're opinion may help me understand

**Comment by wraithgar** [comment]
I'm not sure what you mean by deleted? You can define the userlimit in the config you pass to the module when you instantiate it https://github.com/wraithgar/hapi-rate-limit#options

**Comment by jrcastillo** [comment]
Sorry I did not explain myself well enough.
My question is the following: Why can't user options be overridden at specific routes ?

If I set these global options:
```js
server.register({
    register: require('hapi-rate-limit'),
    options: {
    	userLimit : false
         :
         :
         :
    }
});
```
And then try to set a route options like this:
```js
plugins: {
        'hapi-rate-limit': {
            userLimit:  10,
            :
            :
        }
    }
```

The user limit wont be taken into consideration just as https://github.com/wraithgar/hapi-rate-limit/blob/master/lib/index.js#L159 through https://github.com/wraithgar/hapi-rate-limit/blob/master/lib/index.js#L159 specifies.

Which raises my main question, is there any specific reason for which this was done, regarding security issues or anything beyond a normal restriction ?

**Comment by wraithgar** [comment]
Yes this was deliberate but not because of security settings.  It was because of the nature of how user requests are stored. They are stored per user, not per user+route.  So it didn't make sense to me as I was sketching this out to have a per-route user limit override.

If a user is logged in, the pathLimit is for that user. Perhaps this is sufficient for what you're looking for?

**Comment by jrcastillo** [comment]
Ohh ok, I understand now. Uhm it's not enough because I have public/anonymous routes which after giving it some thoughts made me realize that there must be two types of constraints since the path can only handle such load it would be wise to constraint by user and by route. 

This was my thought "A user shouldn't be able to request make more than X request in Y instance, and a route shouldn't be handling more than X requests in Y instance".

**Comment by wraithgar** [comment]
Ok sorry it's been awhile since I actually looked at this module.  Sorry for the confusion my rustiness has caused.

pathLimit sets the limit for the path in total, regardless of where that request comes from.
userLimit limits for all paths combinded per user. If the route is authenticated, the authenticated user is used. If the route is not authenticated, the remote IP is used.

In order for a per-route AND per-user limit to be implemented, it would need to be a third item that is neither userLimit nor pathLimit.

**Comment by jrcastillo** [comment]
No problem :smile:. Ohh ok so it would need to be implemented then. 

Thanks for the help

**Comment by weyert** [comment]
@jrcastillo Did you end up implementing this?

**Comment by jrcastillo** [comment]
Sorry @weyert, I haven't looked into this

**Comment by wraithgar** [comment]
I belive the userPath limit handles this, it is a per-user+path limit
