### ISSUE TITLE
Path limits are not showing in headers on 403 and 400

### ISSUE THREAD

**Issue by Cheprer** [wraithgar/hapi-rate-limit#33]
Hi there,

I've noticed that the path limits are not showing when trying to e.g. login and receiving 403 but functionality is alright it shows these headers after you are over the limit which is alright.  
```
X-RateLimit-PathLimit:50
X-RateLimit-PathRemaining:-5
X-RateLimit-PathReset:1498639150969
```

For 400 response neither of path and user limits are not show.

Not sure if it's an issue or it is intentionally hidden for these response?

**Comment by wraithgar** [comment]
The reason this happens is because the module currently only hooks into the `onPostAuth` event, which does not fire if authentication fails.  A refactor would need to be done to have the path check (and perhaps the IP portion of the user check) done before auth.

**Comment by wraithgar** [comment]
This still fires on postAuth so the issue stands specifically with auth failures, not with general errors from the handlers themselves.

**Comment by wraithgar** [comment]
After talking this through with @nlf (thanks nlf). I think this issue is ok now. Headers will show up on boom responses, and the thing we're protecting here is your handler, we are limiting how often your handler is ran.  Rate limiting your auth validation function is a separate problem and I'll be making a new issue for that.

**Comment by Cheprer** [comment]
ok thanks :+1:
